import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { EmptyState, LoadingState } from '../../../../../components/States';
import { getAuthorChapters } from '../../../../../services/authors';
import { Chapter } from '../../../../../types';

export default function AuthorChapterListScreen() {
  const router = useRouter(); const { bookId } = useLocalSearchParams<{ bookId: string }>(); const [chapters, setChapters] = useState<Chapter[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setChapters(await getAuthorChapters(bookId)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể tải bản thảo.'); } finally { setLoading(false); } }, [bookId]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const drafts = chapters.filter((chapter) => chapter.status === 'draft').length;
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable style={styles.back} onPress={() => router.back()}><Ionicons name="arrow-back" size={22} color="#2D2327" /></Pressable><View style={styles.headCopy}><Text style={styles.title}>Quản lý chương</Text><Text style={styles.subtitle}>{drafts} bản nháp · {chapters.length - drafts} đã xuất bản</Text></View><Pressable style={styles.add} onPress={() => router.push({ pathname: '/author/books/[bookId]/chapters/[chapterId]', params: { bookId, chapterId: 'new' } })}><Ionicons name="add" size={20} color="#FFFFFF" /></Pressable></View>
    <ScrollView contentContainerStyle={styles.page}>{loading ? <LoadingState label="Đang tải bản thảo…" /> : error ? <EmptyState title="Không tải được chương" detail={error} /> : chapters.length === 0 ? <EmptyState title="Chưa có chương" detail="Tạo bản nháp đầu tiên cho truyện này." /> : chapters.map((chapter) => <Pressable key={chapter.id} style={styles.row} onPress={() => router.push({ pathname: '/author/books/[bookId]/chapters/[chapterId]', params: { bookId, chapterId: chapter.id! } })}><View style={[styles.number, chapter.status === 'published' && styles.numberPublished]}><Text style={styles.numberText}>{chapter.number}</Text></View><View style={styles.copy}><Text numberOfLines={1} style={styles.chapterTitle}>{chapter.title}</Text><Text style={styles.meta}>{chapter.status === 'published' ? 'Đã xuất bản' : 'Bản nháp'} · {(chapter.content?.length ?? 0).toLocaleString('vi-VN')} ký tự</Text></View><Ionicons name="chevron-forward" size={17} color="#A79B9F" /></Pressable>)}</ScrollView>
  </SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F8F2E9' }, header: { height: 63, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#DED1CA' }, back: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' }, headCopy: { flex: 1, marginLeft: 5 }, title: { color: '#291F23', fontSize: 17, fontWeight: '900' }, subtitle: { color: '#81757A', fontSize: 9, marginTop: 2 }, add: { width: 37, height: 37, borderRadius: 19, backgroundColor: '#8F1D3F', alignItems: 'center', justifyContent: 'center' }, page: { paddingHorizontal: 16, paddingBottom: 40, maxWidth: 720, width: '100%', alignSelf: 'center' }, row: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: 11, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#DED2CB' }, number: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#EEE5E1', alignItems: 'center', justifyContent: 'center' }, numberPublished: { backgroundColor: '#E2ECE2' }, numberText: { color: '#8F1D3F', fontSize: 11, fontWeight: '900' }, copy: { flex: 1 }, chapterTitle: { color: '#2D2327', fontSize: 13, fontWeight: '900' }, meta: { color: '#81757A', fontSize: 9, marginTop: 4 } });
