-- CHUONG Admin: merge/update existing books from ZIP by normalized title.
-- Existing book identity, views, followers, pricing, VIP and cover are preserved.
-- Matching chapter numbers are overwritten, new chapter numbers are inserted,
-- and old chapters missing from the ZIP are kept.
begin;

create table if not exists private.chapter_zip_update_backups (
  id bigint generated by default as identity primary key,
  run_id uuid not null,
  admin_user_id uuid,
  book_id uuid not null references public.books(id) on delete cascade,
  chapter_id uuid not null references public.chapters(id) on delete cascade,
  chapter_number integer not null,
  original_title text not null,
  original_content text not null,
  original_status public.chapter_status not null,
  original_published_at timestamptz,
  created_at timestamptz not null default now(),
  unique(run_id,chapter_id)
);

create index if not exists chapter_zip_update_backups_book_idx
  on private.chapter_zip_update_backups(book_id,created_at desc);
create index if not exists chapter_zip_update_backups_run_idx
  on private.chapter_zip_update_backups(run_id);

create or replace function public.admin_match_zip_books(p_titles text[])
returns table(
  input_title text,
  book_id uuid,
  book_title text,
  chapter_count integer,
  has_cover boolean
)
language plpgsql
security definer
set search_path=''
as $$
begin
  if auth.uid() is null or not private.is_admin() then
    raise exception 'admin_required' using errcode='42501';
  end if;
  if coalesce(array_length(p_titles,1),0)=0 then return; end if;
  if array_length(p_titles,1)>200 then raise exception 'too_many_titles'; end if;

  return query
  with requested as (
    select trim(t.title) as input_title,
           private.search_normalize(trim(t.title)) as title_key
    from unnest(p_titles) as t(title)
    where trim(coalesce(t.title,''))<>''
  )
  select r.input_title,b.id,b.title,
         coalesce(b.total_chapters,0)::integer,
         nullif(trim(coalesce(b.cover_url,'')),'') is not null
  from requested r
  join public.books b
    on private.search_normalize(b.title)=r.title_key
  order by r.input_title,b.created_at,b.id;
end;
$$;

create or replace function public.admin_merge_zip_book(
  p_book_id uuid,
  p_title text,
  p_author text,
  p_summary text,
  p_genres text[],
  p_status text,
  p_source_type text,
  p_publish_now boolean,
  p_chapters jsonb
)
returns table(
  run_id uuid,
  book_id uuid,
  replaced_chapters integer,
  added_chapters integer,
  total_chapters integer
)
language plpgsql
security definer
set search_path=''
as $$
declare
  v_run uuid:=gen_random_uuid();
  v_item jsonb;
  v_number integer;
  v_title text;
  v_content text;
  v_existing public.chapters%rowtype;
  v_replaced integer:=0;
  v_added integer:=0;
  v_total integer:=0;
  v_genres text[];
  v_allowed constant text[]:=array[
    'Xuyên không','Trọng sinh','Hệ thống','Tiên hiệp','Huyền huyễn','Mạt thế',
    'Đam mỹ','Ngôn tình','Cổ đại','Cung đấu','Đô thị','Giới giải trí',
    'Huyền học','Trinh thám','Kinh dị','Khoa huyễn','Esports','Kiếm hiệp',
    'Fantasy','Điền văn','Vô hạn lưu','Niên đại','Văn học','Khác'
  ];
begin
  if auth.uid() is null or not private.is_admin() then
    raise exception 'admin_required' using errcode='42501';
  end if;
  if not exists(select 1 from public.books b where b.id=p_book_id) then
    raise exception 'book_not_found';
  end if;
  if jsonb_typeof(p_chapters)<>'array' or jsonb_array_length(p_chapters)=0 then
    raise exception 'chapters_required';
  end if;
  if jsonb_array_length(p_chapters)>5000 then raise exception 'too_many_chapters'; end if;

  -- Keep the existing book identity and commercial/social data. Only refresh
  -- safe catalog metadata coming from the newly uploaded ZIP.
  update public.books b
  set title=coalesce(nullif(trim(p_title),''),b.title),
      credited_author_name=case
        when nullif(trim(coalesce(p_author,'')),'') is null then b.credited_author_name
        when nullif(trim(coalesce(b.credited_author_name,'')),'') is null
          or lower(trim(b.credited_author_name))='chuong'
          then trim(p_author)
        else b.credited_author_name
      end,
      description=case
        when nullif(trim(coalesce(p_summary,'')),'') is not null
          and (trim(coalesce(b.description,''))='' or b.description='Hãy khám phá.')
          then trim(p_summary)
        else b.description
      end,
      source_type=coalesce(nullif(trim(p_source_type),'')::public.source_type,b.source_type),
      status=case when p_publish_now then coalesce(nullif(trim(p_status),'')::public.book_status,b.status) else b.status end,
      visibility=case when p_publish_now then 'public'::public.book_visibility else b.visibility end,
      updated_at=now()
  where b.id=p_book_id;

  select coalesce(array_agg(distinct g order by g),array[]::text[])
  into v_genres
  from (
    select trim(g) as g
    from unnest(coalesce(p_genres,array[]::text[])) g
    where trim(g)=any(v_allowed)
    limit 3
  ) x;

  if coalesce(array_length(v_genres,1),0)>0 then
    delete from public.book_genres bg where bg.book_id=p_book_id;
    insert into public.book_genres(book_id,genre)
    select p_book_id,g from unnest(v_genres) g;
  end if;

  for v_item in select value from jsonb_array_elements(p_chapters) loop
    v_number:=coalesce((v_item->>'chapterNumber')::integer,(v_item->>'chapter_number')::integer);
    v_title:=trim(coalesce(v_item->>'title',''));
    v_content:=coalesce(v_item->>'content','');

    if v_number is null or v_number<1 then raise exception 'invalid_chapter_number'; end if;
    if trim(v_content)='' then raise exception 'empty_chapter_%',v_number; end if;

    select * into v_existing
    from public.chapters c
    where c.book_id=p_book_id and c.chapter_number=v_number
    for update;

    if found then
      insert into private.chapter_zip_update_backups(
        run_id,admin_user_id,book_id,chapter_id,chapter_number,
        original_title,original_content,original_status,original_published_at
      ) values (
        v_run,auth.uid(),p_book_id,v_existing.id,v_existing.chapter_number,
        v_existing.title,v_existing.content,v_existing.status,v_existing.published_at
      );

      update public.chapters c
      set title=v_title,
          content=v_content,
          status=case when p_publish_now then 'published'::public.chapter_status else c.status end,
          published_at=case
            when p_publish_now then coalesce(c.published_at,now())
            else c.published_at
          end,
          updated_at=now()
      where c.id=v_existing.id;
      v_replaced:=v_replaced+1;
    else
      insert into public.chapters(
        book_id,chapter_number,title,content,status,is_vip,price_coins,published_at
      ) values (
        p_book_id,v_number,v_title,v_content,
        case when p_publish_now then 'published'::public.chapter_status else 'draft'::public.chapter_status end,
        false,0,case when p_publish_now then now() else null end
      );
      v_added:=v_added+1;
    end if;
  end loop;

  select count(*)::integer into v_total from public.chapters c where c.book_id=p_book_id;
  update public.books b set total_chapters=v_total,updated_at=now() where b.id=p_book_id;

  return query select v_run,p_book_id,v_replaced,v_added,v_total;
end;
$$;

create or replace function public.admin_restore_zip_update(p_run_id uuid)
returns table(restored_chapters integer)
language plpgsql
security definer
set search_path=''
as $$
declare
  v_count integer:=0;
begin
  if auth.uid() is null or not private.is_admin() then
    raise exception 'admin_required' using errcode='42501';
  end if;

  update public.chapters c
  set title=b.original_title,
      content=b.original_content,
      status=b.original_status,
      published_at=b.original_published_at,
      updated_at=now()
  from private.chapter_zip_update_backups b
  where b.run_id=p_run_id and b.chapter_id=c.id;
  get diagnostics v_count=row_count;
  return query select v_count;
end;
$$;

revoke all on function public.admin_match_zip_books(text[]) from public,anon;
revoke all on function public.admin_merge_zip_book(uuid,text,text,text,text[],text,text,boolean,jsonb) from public,anon;
revoke all on function public.admin_restore_zip_update(uuid) from public,anon;
grant execute on function public.admin_match_zip_books(text[]) to authenticated;
grant execute on function public.admin_merge_zip_book(uuid,text,text,text,text[],text,text,boolean,jsonb) to authenticated;
grant execute on function public.admin_restore_zip_update(uuid) to authenticated;

commit;
