-- CHUONG Admin: reclassify existing books and clean scraped boilerplate from chapters.
-- Destructive chapter cleanup is backed up in private.chapter_content_cleanup_backups.

begin;

create table if not exists private.chapter_content_cleanup_backups (
  id bigint generated by default as identity primary key,
  run_id uuid not null,
  admin_user_id uuid,
  book_id uuid not null references public.books(id) on delete cascade,
  chapter_id uuid not null references public.chapters(id) on delete cascade,
  original_content text not null,
  removed_line_count integer not null default 0,
  removed_samples text[] not null default array[]::text[],
  created_at timestamptz not null default now(),
  unique(run_id, chapter_id)
);

create index if not exists chapter_content_cleanup_backups_book_idx
  on private.chapter_content_cleanup_backups(book_id, created_at desc);
create index if not exists chapter_content_cleanup_backups_run_idx
  on private.chapter_content_cleanup_backups(run_id);

create or replace function private.is_story_junk_line(p_line text)
returns boolean
language plpgsql
immutable
set search_path = ''
as $$
declare
  v text := lower(trim(coalesce(p_line,'')));
begin
  if v = '' then return false; end if;

  -- Scraped reader controls / obvious boilerplate.
  if char_length(v) <= 220 and (
    v ~ '^(chữ to|chu to).*(chữ nhỏ|chu nho)$'
    or v ~ '^(chương trước|chuong truoc|chương sau|chuong sau|mục lục|muc luc|đọc tiếp|doc tiep|trang chủ|trang chu|quảng cáo|quang cao)[[:space:][:punct:]]*$'
  ) then return true; end if;

  -- URLs and known reading-site watermarks are not story prose.
  if char_length(v) <= 600 and (
    v ~ '(https?://|www\.)'
    or v ~ '(^|[^[:alnum:]_])(truyenfull|metruyenchu|wikidich|tangthuvien|bachngocsach|sstruyen|dtruyen|truyenyy|truyencv|wattpad|wordpress|noveltoon|webtruyen)([^[:alnum:]_]|$)'
  ) then return true; end if;

  -- Source / editor / repost / group promotion lines.
  if char_length(v) <= 600 and v ~
    '^(nguồn|source|convert|converter|edit|editor|dịch|dich|beta|raw|reup|đăng tại|dang tai|đọc tại|doc tai|đọc truyện tại|doc truyen tai|website|web truyện|web truyen|truyện được đăng|truyen duoc dang|truyện được lấy|truyen duoc lay|tham gia nhóm|tham gia group|join group|fanpage|facebook|telegram|zalo)[[:space:][:punct:]]'
  then return true; end if;

  if char_length(v) <= 600 and v ~
    '(vui lòng không reup|vui long khong reup|không reup|khong reup|không copy|khong copy|cấm reup|cam reup|cấm sao chép|cam sao chep|ủng hộ team|ung ho team|ủng hộ editor|ung ho editor)'
  then return true; end if;

  -- Donation / bank-account boilerplate: require both payment language and
  -- either an account-like number or a bank/payment marker.
  if char_length(v) <= 600
     and v ~ '(^|[[:space:][:punct:]])(stk|số tài khoản|so tai khoan|chuyển khoản|chuyen khoan|momo|paypal|donate|ủng hộ|ung ho)([[:space:][:punct:]]|$)'
     and (
       v ~ '[0-9][0-9 .-]{5,}[0-9]'
       or v ~ '(qr|bank|ngân hàng|ngan hang|vietcombank|techcombank|mbbank|mb bank|tpbank|bidv|vpbank|acb|vib|sacombank)'
     )
  then return true; end if;

  return false;
end;
$$;

create or replace function private.story_junk_line_count(p_content text)
returns integer
language sql
immutable
set search_path = ''
as $$
  select count(*)::integer
  from regexp_split_to_table(coalesce(p_content,''), E'\\r?\\n') as x(line)
  where private.is_story_junk_line(x.line);
$$;

create or replace function private.story_junk_samples(p_content text, p_limit integer default 8)
returns text[]
language sql
immutable
set search_path = ''
as $$
  select coalesce(array_agg(sample order by ord), array[]::text[])
  from (
    select left(trim(x.line),180) as sample, min(x.ord) as ord
    from regexp_split_to_table(coalesce(p_content,''), E'\\r?\\n') with ordinality as x(line,ord)
    where private.is_story_junk_line(x.line)
    group by left(trim(x.line),180)
    order by min(x.ord)
    limit greatest(1,least(coalesce(p_limit,8),20))
  ) s;
$$;

create or replace function private.clean_story_text(p_content text)
returns text
language sql
immutable
set search_path = ''
as $$
  with lines as (
    select x.line,x.ord
    from regexp_split_to_table(coalesce(p_content,''), E'\\r?\\n') with ordinality as x(line,ord)
  ),
  kept as (
    select case when private.is_story_junk_line(line) then '' else line end as line, ord
    from lines
  ),
  joined as (
    select string_agg(line,E'\n' order by ord) as body from kept
  )
  select trim(both E'\n' from regexp_replace(coalesce(body,''), E'\n{3,}', E'\n\n', 'g'))
  from joined;
$$;

create or replace function public.admin_genre_scan_inputs(p_book_ids uuid[])
returns table(
  book_id uuid,
  title text,
  description text,
  sample_text text
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or not private.is_admin() then
    raise exception 'admin_required' using errcode='42501';
  end if;
  if coalesce(array_length(p_book_ids,1),0)=0 then return; end if;
  if array_length(p_book_ids,1)>100 then raise exception 'too_many_books'; end if;

  return query
  select b.id,b.title,coalesce(b.description,''),
    coalesce((
      select string_agg(left(q.content,6500), E'\n\n' order by q.chapter_number)
      from (
        select c.chapter_number,c.content
        from public.chapters c
        where c.book_id=b.id
        order by c.chapter_number
        limit 3
      ) q
    ),'') as sample_text
  from public.books b
  where b.id=any(p_book_ids)
  order by b.title,b.id;
end;
$$;

create or replace function public.admin_apply_book_genres(p_updates jsonb)
returns table(book_id uuid, genres text[], success boolean, message text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_item jsonb;
  v_id uuid;
  v_genres text[];
  v_allowed constant text[] := array[
    'Xuyên không','Trọng sinh','Hệ thống','Tiên hiệp','Huyền huyễn','Mạt thế',
    'Đam mỹ','Ngôn tình','Cổ đại','Cung đấu','Đô thị','Giới giải trí',
    'Huyền học','Trinh thám','Kinh dị','Khoa huyễn','Esports','Kiếm hiệp',
    'Fantasy','Điền văn','Vô hạn lưu','Niên đại','Văn học','Khác'
  ];
begin
  if auth.uid() is null or not private.is_admin() then
    raise exception 'admin_required' using errcode='42501';
  end if;
  if jsonb_typeof(p_updates) <> 'array' then raise exception 'invalid_updates'; end if;
  if jsonb_array_length(p_updates)>100 then raise exception 'too_many_books'; end if;

  for v_item in select value from jsonb_array_elements(p_updates) loop
    begin
      v_id := (v_item->>'book_id')::uuid;
      select coalesce(array_agg(distinct g order by g),array[]::text[])
      into v_genres
      from (
        select trim(value) g
        from jsonb_array_elements_text(coalesce(v_item->'genres','[]'::jsonb))
        where trim(value)=any(v_allowed)
        limit 3
      ) x;

      if coalesce(array_length(v_genres,1),0)=0 then v_genres:=array['Khác']; end if;
      if not exists(select 1 from public.books b where b.id=v_id) then
        book_id:=v_id;genres:=v_genres;success:=false;message:='Không tìm thấy truyện';return next;continue;
      end if;

      delete from public.book_genres bg where bg.book_id=v_id;
      insert into public.book_genres(book_id,genre)
      select v_id,g from unnest(v_genres) g;

      book_id:=v_id;genres:=v_genres;success:=true;message:='Đã phân loại lại';return next;
    exception when others then
      book_id:=v_id;genres:=coalesce(v_genres,array[]::text[]);success:=false;message:=sqlerrm;return next;
    end;
  end loop;
end;
$$;

create or replace function public.admin_content_hygiene_preview(p_book_ids uuid[])
returns table(
  book_id uuid,
  title text,
  total_chapters integer,
  affected_chapters integer,
  junk_lines integer,
  sample_lines text[]
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or not private.is_admin() then
    raise exception 'admin_required' using errcode='42501';
  end if;
  if coalesce(array_length(p_book_ids,1),0)=0 then return; end if;
  if array_length(p_book_ids,1)>100 then raise exception 'too_many_books'; end if;

  return query
  with chapter_stats as (
    select c.book_id,c.id,
      private.story_junk_line_count(c.content) as bad_lines,
      private.story_junk_samples(c.content,4) as samples
    from public.chapters c
    where c.book_id=any(p_book_ids)
  ),
  agg as (
    select cs.book_id,
      count(*)::integer total_chapters,
      count(*) filter(where cs.bad_lines>0)::integer affected_chapters,
      coalesce(sum(cs.bad_lines),0)::integer junk_lines,
      coalesce((
        select array_agg(distinct s order by s)
        from chapter_stats cs2
        cross join lateral unnest(cs2.samples) s
        where cs2.book_id=cs.book_id
      ),array[]::text[]) as sample_lines
    from chapter_stats cs
    group by cs.book_id
  )
  select b.id,b.title,
    coalesce(a.total_chapters,0),
    coalesce(a.affected_chapters,0),
    coalesce(a.junk_lines,0),
    coalesce(a.sample_lines,array[]::text[])[1:8]
  from public.books b
  left join agg a on a.book_id=b.id
  where b.id=any(p_book_ids)
  order by b.title,b.id;
end;
$$;

create or replace function public.admin_clean_story_junk(p_book_ids uuid[])
returns table(
  run_id uuid,
  books_scanned integer,
  chapters_scanned integer,
  chapters_changed integer,
  junk_lines_removed integer,
  chapters_skipped integer
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_run uuid := gen_random_uuid();
  v_ch record;
  v_clean text;
  v_removed integer;
  v_changed integer := 0;
  v_removed_total integer := 0;
  v_skipped integer := 0;
  v_scanned integer := 0;
begin
  if auth.uid() is null or not private.is_admin() then
    raise exception 'admin_required' using errcode='42501';
  end if;
  if coalesce(array_length(p_book_ids,1),0)=0 then
    return query select v_run,0,0,0,0,0; return;
  end if;
  if array_length(p_book_ids,1)>100 then raise exception 'too_many_books'; end if;

  for v_ch in
    select c.id,c.book_id,c.content
    from public.chapters c
    where c.book_id=any(p_book_ids)
    order by c.book_id,c.chapter_number
  loop
    v_scanned:=v_scanned+1;
    v_removed:=private.story_junk_line_count(v_ch.content);
    if v_removed<=0 then continue; end if;

    v_clean:=private.clean_story_text(v_ch.content);

    -- Never turn a normal chapter into an empty/tiny chapter automatically.
    if char_length(trim(v_clean))<50 and char_length(trim(coalesce(v_ch.content,'')))>=50 then
      v_skipped:=v_skipped+1;
      continue;
    end if;

    insert into private.chapter_content_cleanup_backups(
      run_id,admin_user_id,book_id,chapter_id,original_content,removed_line_count,removed_samples
    ) values (
      v_run,auth.uid(),v_ch.book_id,v_ch.id,v_ch.content,v_removed,private.story_junk_samples(v_ch.content,8)
    );

    update public.chapters c set content=v_clean where c.id=v_ch.id;
    v_changed:=v_changed+1;
    v_removed_total:=v_removed_total+v_removed;
  end loop;

  return query
  select v_run,
    coalesce(array_length(p_book_ids,1),0),
    v_scanned,
    v_changed,
    v_removed_total,
    v_skipped;
end;
$$;

create or replace function public.admin_restore_story_cleanup(p_run_id uuid)
returns table(chapters_restored integer)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer;
begin
  if auth.uid() is null or not private.is_admin() then
    raise exception 'admin_required' using errcode='42501';
  end if;

  update public.chapters c
  set content=b.original_content
  from private.chapter_content_cleanup_backups b
  where b.run_id=p_run_id and b.chapter_id=c.id;
  get diagnostics v_count=row_count;
  return query select v_count;
end;
$$;

revoke all on function public.admin_genre_scan_inputs(uuid[]) from public,anon;
revoke all on function public.admin_apply_book_genres(jsonb) from public,anon;
revoke all on function public.admin_content_hygiene_preview(uuid[]) from public,anon;
revoke all on function public.admin_clean_story_junk(uuid[]) from public,anon;
revoke all on function public.admin_restore_story_cleanup(uuid) from public,anon;

grant execute on function public.admin_genre_scan_inputs(uuid[]) to authenticated;
grant execute on function public.admin_apply_book_genres(jsonb) to authenticated;
grant execute on function public.admin_content_hygiene_preview(uuid[]) to authenticated;
grant execute on function public.admin_clean_story_junk(uuid[]) to authenticated;
grant execute on function public.admin_restore_story_cleanup(uuid) to authenticated;

commit;
