name: Deploy Admin Upload Web

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: admin-pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload static Admin site
        uses: actions/upload-pages-artifact@v3
        with:
          path: admin-web
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
